# Create a z-score table

In [ ]:
import numpy as np
import pandas as pd
from scipy.integrate import quad

In [ ]:
def normal_probability_density(x):
    constant = 1.0 / np.sqrt(2 * np.pi)
    return(constant * np.exp((-x**2) / 2))

In [ ]:
standard_normal_table = pd.DataFrame(data=[],
                                     index = np.round(np.arange(0, 3.5, .1), 2),
                                     columns=np.round(np.arange(0.00, 0.1, 0.01), 2))

for index in standard_normal_table.index:
  for column in standard_normal_table.columns:
    z = np.round(index + column, 2)
    value, _ = quad(normal_probability_density, np.NINF, z)
    standard_normal_table.loc[index, column] = value

standard_normal_table.index = standard_normal_table.index.astype(str)
standard_normal_table.columns = (str(column).ljust(4, '0') for column in standard_normal_table.columns)

standard_normal_table

,0.00,0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09
0.0,0.5,0.503989,0.507978,0.511966,0.515953,0.519939,0.523922,0.527903,0.531881,0.535856
0.1,0.539828,0.543795,0.547758,0.551717,0.55567,0.559618,0.563559,0.567495,0.571424,0.575345
0.2,0.57926,0.583166,0.587064,0.590954,0.594835,0.598706,0.602568,0.60642,0.610261,0.614092
0.3,0.617911,0.62172,0.625516,0.6293,0.633072,0.636831,0.640576,0.644309,0.648027,0.651732
0.4,0.655422,0.659097,0.662757,0.666402,0.670031,0.673645,0.677242,0.680822,0.684386,0.687933
0.5,0.691462,0.694974,0.698468,0.701944,0.705401,0.70884,0.71226,0.715661,0.719043,0.722405
0.6,0.725747,0.729069,0.732371,0.735653,0.738914,0.742154,0.745373,0.748571,0.751748,0.754903
0.7,0.758036,0.761148,0.764238,0.767305,0.77035,0.773373,0.776373,0.77935,0.782305,0.785236
0.8,0.788145,0.79103,0.793892,0.796731,0.799546,0.802337,0.805105,0.80785,0.81057,0.813267
0.9,0.81594,0.818589,0.821214,0.823814,0.826391,0.828944,0.831472,0.833977,0.836457,0.838913
1.0,0.841345,0.843752,0.846136,0.848495,0.85083,0.853141,0.855428,0.85769,0.859929,0.862143
1.1,0.864334,0.8665,0.868643,0.870762,0.872857,0.874928,0.876976,0.879,0.881,0.882977
1.2,0.88493,0.886861,0.888768,0.890651,0.892512,0.89435,0.896165,0.897958,0.899727,0.901475
1.3,0.9032,0.904902,0.906582,0.908241,0.909877,0.911492,0.913085,0.914657,0.916207,0.917736
1.4,0.919243,0.92073,0.922196,0.923641,0.925066,0.926471,0.927855,0.929219,0.930563,0.931888
1.5,0.933193,0.934478,0.935745,0.936992,0.93822,0.939429,0.94062,0.941792,0.942947,0.944083
1.6,0.945201,0.946301,0.947384,0.948449,0.949497,0.950529,0.951543,0.95254,0.953521,0.954486
1.7,0.955435,0.956367,0.957284,0.958185,0.95907,0.959941,0.960796,0.961636,0.962462,0.963273
1.8,0.96407,0.964852,0.96562,0.966375,0.967116,0.967843,0.968557,0.969258,0.969946,0.970621
1.9,0.971283,0.971933,0.972571,0.973197,0.97381,0.974412,0.975002,0.975581,0.976148,0.976705
2.0,0.97725,0.977784,0.978308,0.978822,0.979325,0.979818,0.980301,0.980774,0.981237,0.981691
2.1,0.982136,0.982571,0.982997,0.983414,0.983823,0.984222,0.984614,0.984997,0.985371,0.985738
2.2,0.986097,0.986447,0.986791,0.987126,0.987455,0.987776,0.988089,0.988396,0.988696,0.988989
2.3,0.989276,0.989556,0.98983,0.990097,0.990358,0.990613,0.990863,0.991106,0.991344,0.991576
2.4,0.991802,0.992024,0.99224,0.992451,0.992656,0.992857,0.993053,0.993244,0.993431,0.993613
2.5,0.99379,0.993963,0.994132,0.994297,0.994457,0.994614,0.994766,0.994915,0.99506,0.995201
2.6,0.995339,0.995473,0.995604,0.995731,0.995855,0.995975,0.996093,0.996207,0.996319,0.996427
2.7,0.996533,0.996636,0.996736,0.996833,0.996928,0.99702,0.99711,0.997197,0.997282,0.997365
2.8,0.997445,0.997523,0.997599,0.997673,0.997744,0.997814,0.997882,0.997948,0.998012,0.998074
2.9,0.998134,0.998193,0.99825,0.998305,0.998359,0.998411,0.998462,0.998511,0.998559,0.998605
3.0,0.99865,0.998694,0.998736,0.998777,0.998817,0.998856,0.998893,0.99893,0.998965,0.998999
3.1,0.999032,0.999065,0.999096,0.999126,0.999155,0.999184,0.999211,0.999238,0.999264,0.999289
3.2,0.999313,0.999336,0.999359,0.999381,0.999402,0.999423,0.999443,0.999462,0.999481,0.999499
3.3,0.999517,0.999534,0.99955,0.999566,0.999581,0.999596,0.99961,0.999624,0.999638,0.999651
3.4,0.999663,0.999675,0.999687,0.999698,0.999709,0.99972,0.99973,0.99974,0.999749,0.999758

# T-student test from two datasets

In [ ]:
# packages

from math import sqrt
from numpy.random import seed
from numpy.random import randn
from numpy import mean
from scipy.stats import sem
from scipy.stats import t

In [ ]:
# input data

seed(1)
dataset_1 = 6 * randn(300) + 30
dataset_2 = 6 * randn(300) + 40
alpha = 0.05

In [ ]:
# t_test function calculator

def t_test(dataset_1: list, dataset_2: list, alpha: float) -> float:
  """Calculate T test from two dataset
  dataset_1: [list] the first dataset
  dataset_2: [list] the second dataset

  return: [int] the p-value for the distributions
  """
  mean_1, mean_2 = mean(dataset_1), mean(dataset_2)

  stand_err_1, stand_err_2 = sem(dataset_1), sem(dataset_2)

  stand_err_diff = sqrt(stand_err_1**2 + stand_err_2**2)

  t_stat = (mean_1 - mean_2) / stand_err_diff

  df = (len(dataset_1) + len(dataset_2)) - 2

  critical = t.ppf(1 - alpha, df)

  p_value = (1 - t.cdf(abs(t_stat), df)) * 2

  return t_stat, df, critical, p_value

In [ ]:
# solve for input values

t_stat, df, critical, p_value = t_test(dataset_1, dataset_2, alpha)

print(f"t_stat = {t_stat:.2f}, df = {df}, critical = {critical:.2f}, p-value = {p_value:.4f}")

t_stat = -20.20, df = 598, critical = 1.65, p-value = 0.0000

In [ ]:
# critical value test

if abs(t_stat) <= critical:
  print("accept H0")
else:
  print("reject H0")

reject H0

In [ ]:
# p-value test
if p_value > alpha:
    print("accept H0")
else:
  print("reject H0")

reject H0